cloud:
  aws:
    region:
      static: ap-south-1
      auto: false
    credentials:
      access-key: put user access key
      secret-key: put user secret key
    end-point:
      uri: put required SQS url